stages:
  - publish_to_dev

stage:
  image: node:latest
  stage: publish_to_dev
  before_script:
    - npm install -g fern-api
  variables:
    FERN_TOKEN: $FERN_TOKEN
  script:
    - fern generate --docs --instance dev-fyno.docs.buildwithfern.com/docs
  only:
    refs:      
      - /^25\..*/