name: Publish Docs

on:
  push:
    branches:
      - main
      - "25.**"
  pull_request:
    branches:
      - main      

jobs:
  publish-docs:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            fern generate --docs --instance fyno.docs.buildwithfern.com/docs
          elif [[ "${{ github.ref }}" =~ refs/heads/25\..* || "${{ github.event_name }}" == "pull_request" ]]; then
            fern generate --docs --instance dev-fyno.docs.buildwithfern.com/docs 
          fi

      - name: Comment Preview URL (Commit)
        uses: peter-evans/commit-comment@v3
        if: startsWith(github.ref, 'refs/heads/25.')
        with:
            body: "[Test] Build deplolyed: https://dev-fyno.docs.buildwithfern.com/docs"

      - name: Comment Preview URL (PR)
        uses: thollander/actions-comment-pull-request@v2.4.3
        if: github.event_name == 'pull_request'
        with:
            message: "[Test] Build deplolyed: https://dev-fyno.docs.buildwithfern.com/docs"

      - name: Comment Progress in Commit
        uses: peter-evans/commit-comment@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
            body: "[Prod] Build deployed: https://fyno.io/docs"
