name: Publish Docs

on:
  push:
    branches:
      - main
      - "25.**"

jobs:
  publish-docs:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            fern generate --docs
          elif [[ "${{ github.ref }}" =~ refs/heads/25\..* ]]; then
            fern generate --docs --preview
          fi
