name: Publish Docs

on:
  push:
    branches:
      - main
      - "25.**"

jobs:
  publish-docs:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            fern generate --docs
          elif [[ "${{ github.ref }}" =~ refs/heads/25\..* ]]; then
            OUTPUT=$(fern generate --docs --preview 2>&1) || true
            echo "$OUTPUT"
            URL=$(echo "$OUTPUT" | grep -oP 'Published docs to \K.*(?= \()')
            echo "Preview URL: $URL"
            echo "Preview your docs: $URL" > preview_url.txt
          fi

      - name: Comment URL in Commit
        uses: peter-evans/commit-comment@v3
        if: startsWith(github.ref, 'refs/heads/25.')
        with:
            body-path: "preview_url.txt"

      - name: Comment Progress in PR
        uses: thollander/actions-comment-pull-request@v2.4.3
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        with:
            message: "Build deployed: https://fyno.io/docs"

      - name: Comment Progress in Commit
        uses: peter-evans/commit-comment@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
            body: "Build deployed: https://fyno.io/docs"
